### PR TITLE
open a pull request

### PR DESCRIPTION
**Pull request by thatkookooguy**
# Change Summary

 - change short synopsis I [resolves #00]
   > additional info about this mission
 
 - change short synopsis II (mission without additional info)
 - change short synopsis III
 
## More info

(Free text here with additional photos, wikis, and additional needed information)

### CODE REVIEW

**Comment by ghost** [comment]
There were the following issues with this Pull Request

* Commit: 09a5fc204a70e6e94101d02b71173cb1a2fb8f11
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 54940568dddcf596966608be8a045746e5cae949
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 5e39b1d7d92692dc09e293803100baaf9b46d355
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 071fefc3af5e989d354d240b2fd39defc90e5694
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 8180da6b0264df4983598bef5592103a28e50f76
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: c8d089d5879b9484bad16a3dfcb3a16f489eb5bd
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: ed051ecc7dffa06d576df87d75017b7a8cfc2672
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 3bd47afc71cd65f3851d259622e07e50192d47b5
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 105017ccd883182ebf1f98d0a72cad14748fecac
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 78b5b91916b597f56ae2409626b598afbf4cb8e5
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 645e9b318cbe2cdd3d96352e0b76023e13a26d13
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: a2cb1b5c73c9707e5ec4a136df82fc292b643e9b
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 41cd1026876c19481a3e2c5d1d3a343576abe367
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: ca9e4f1e11d71985e0476043a19ef9ba0b1c1cb4
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: b80cdc18cfd4084dce013ee35ee6fbac4b9d40ea
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 4ee541b900408a92622e8a19b0a7c692abd05958
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: b9e081e7feb76e3d558d8a0651b49635bbb37bde
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 74b7624ef7babea87fe3cf0483e0146f6524cddd
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: c0ad3308d6789bdde7f1a91c1318cb8d30b46fa2
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: f28bfc024a6f3a024dc0681a9728ba3356bfb2bf
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 0615d2134d864712d27c61f53223294aeb12a7f4
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 2002538e52cde1f534986ff247b6af69adca1265
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: df0d8784b884d16d0887cb4930bd0ab6a64d1da5
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 6877b0359005fa57f678419346797b33f6252eb8
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: ae710d2fbc888a341271655d73fd0e89db4da03a
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: bf9d8cfdfd340653132eb0a6787e7949d1b0f26a
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 85662bf7fbe04a8abbae6f55d3232d6991b9cc8a
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: faaddb5f4c8ae303124f03edc9006f65ffe63bd6
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: d7d549a91df0b4d4a192a4d6d479157a3eeb9d11
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 793974edce3b10a18cd5cd1031ea149cac2fc6c9
  - ✖ message may not be empty
  - ✖ type may not be empty


You may need to [change the commit messages][ref] to comply with the repository contributing guidelines.

--------

🤖 This comment was generated by [**commitlint[bot]**][repo]. Please report issues [here][issues].

Happy coding!

[ref]: https://help.github.com/articles/changing-a-commit-message/
[repo]: https://github.com/z0al/commitlint-bot
[issues]: https://github.com/z0al/commitlint-bot/issues

**Comment by ghost** [comment]
There were the following issues with this Pull Request

* Commit: 5a705fc88c700b1f6f6c93ba9c4b80f0c0a8aed7
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 5fc25655158665d4ea576cc7aeeb59ac1edec0f1
  - ✖ message may not be empty
  - ✖ type may not be empty


You may need to [change the commit messages][ref] to comply with the repository contributing guidelines.

--------

🤖 This comment was generated by [**commitlint[bot]**][repo]. Please report issues [here][issues].

Happy coding!

[ref]: https://help.github.com/articles/changing-a-commit-message/
[repo]: https://github.com/z0al/commitlint-bot
[issues]: https://github.com/z0al/commitlint-bot/issues

**Comment by ghost** [comment]
There were the following issues with this Pull Request

* Commit: 09a5fc204a70e6e94101d02b71173cb1a2fb8f11
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 54940568dddcf596966608be8a045746e5cae949
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 5e39b1d7d92692dc09e293803100baaf9b46d355
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 071fefc3af5e989d354d240b2fd39defc90e5694
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 8180da6b0264df4983598bef5592103a28e50f76
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: c8d089d5879b9484bad16a3dfcb3a16f489eb5bd
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: ed051ecc7dffa06d576df87d75017b7a8cfc2672
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 3bd47afc71cd65f3851d259622e07e50192d47b5
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 105017ccd883182ebf1f98d0a72cad14748fecac
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 78b5b91916b597f56ae2409626b598afbf4cb8e5
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 645e9b318cbe2cdd3d96352e0b76023e13a26d13
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: a2cb1b5c73c9707e5ec4a136df82fc292b643e9b
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 41cd1026876c19481a3e2c5d1d3a343576abe367
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: ca9e4f1e11d71985e0476043a19ef9ba0b1c1cb4
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: b80cdc18cfd4084dce013ee35ee6fbac4b9d40ea
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 4ee541b900408a92622e8a19b0a7c692abd05958
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: b9e081e7feb76e3d558d8a0651b49635bbb37bde
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 74b7624ef7babea87fe3cf0483e0146f6524cddd
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: c0ad3308d6789bdde7f1a91c1318cb8d30b46fa2
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: f28bfc024a6f3a024dc0681a9728ba3356bfb2bf
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 0615d2134d864712d27c61f53223294aeb12a7f4
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 2002538e52cde1f534986ff247b6af69adca1265
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: df0d8784b884d16d0887cb4930bd0ab6a64d1da5
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 6877b0359005fa57f678419346797b33f6252eb8
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: ae710d2fbc888a341271655d73fd0e89db4da03a
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: bf9d8cfdfd340653132eb0a6787e7949d1b0f26a
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 85662bf7fbe04a8abbae6f55d3232d6991b9cc8a
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: faaddb5f4c8ae303124f03edc9006f65ffe63bd6
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: d7d549a91df0b4d4a192a4d6d479157a3eeb9d11
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 793974edce3b10a18cd5cd1031ea149cac2fc6c9
  - ✖ message may not be empty
  - ✖ type may not be empty


You may need to [change the commit messages][ref] to comply with the repository contributing guidelines.

--------

🤖 This comment was generated by [**commitlint[bot]**][repo]. Please report issues [here][issues].

Happy coding!

[ref]: https://help.github.com/articles/changing-a-commit-message/
[repo]: https://github.com/z0al/commitlint-bot
[issues]: https://github.com/z0al/commitlint-bot/issues

**Comment by ghost** [comment]
There were the following issues with this Pull Request

* Commit: 5a705fc88c700b1f6f6c93ba9c4b80f0c0a8aed7
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 5fc25655158665d4ea576cc7aeeb59ac1edec0f1
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 9229c4a672623e95ca8c062c36f0635921cd8353
  - ✖ message may not be empty
  - ✖ type may not be empty


You may need to [change the commit messages][ref] to comply with the repository contributing guidelines.

--------

🤖 This comment was generated by [**commitlint[bot]**][repo]. Please report issues [here][issues].

Happy coding!

[ref]: https://help.github.com/articles/changing-a-commit-message/
[repo]: https://github.com/z0al/commitlint-bot
[issues]: https://github.com/z0al/commitlint-bot/issues

**Comment by thatkookooguy** [comment]
closing this because of too many comments :-)

**Pull request closed without merging**
